security:
    # encoders:
    #     App\Entity\User:
    #         algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
        # doctor :
        #     pattern : ^/api/doctors
        #     anonymous : false
        #     stateless : true
        #     guard:
        #         authenticators:
        #             - App\Security\JwtAuthAuthenticator
        doctors_id :
            pattern : ^/api/doctors/
            methods : [GET]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        patients_id :
            pattern : ^/api/patients/
            methods : [GET]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        appointments_create :
            pattern : ^/api/appointments/create
            methods : [POST]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        appointments_doctor_id :
            pattern : ^/api/appointments/doctors
            methods : [GET]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        appointments_patient_id :
            pattern : ^/api/appointments/patients
            methods : [GET]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        appointments_status :
            pattern : ^/api/appointments/status
            methods : [POST]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        appointments_take :
            pattern : ^/api/appointments/take
            methods : [GET]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        logout :
            pattern : ^/api/logout
            methods : [POST]
            anonymous : false
            stateless : true
            guard:
                authenticators:
                    - App\Security\JwtAuthAuthenticator
        main:
            anonymous: true
            provider: app_user_provider
            

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/doctors/, roles: ROLE_DOCTOR, methods: [GET] }
        - { path: ^/api/appointments/create, roles: ROLE_DOCTOR, methods: [POST] }
        - { path: ^/api/appointments/patients, roles: ROLE_PATIENT, methods: [GET] }
        - { path: ^/api/appointments/doctors, roles: ROLE_DOCTOR, methods: [GET] }
        - { path: ^/api/appointments/status, roles: [ROLE_DOCTOR,ROLE_PATIENT], methods: [POST] }
        - { path: ^/api/appointments/take, roles: ROLE_PATIENT, methods: [GET] }
        - { path: ^/api/patients/, roles: ROLE_PATIENT, methods: [GET] }
